-- Attendance Management schema
-- Run this in Supabase SQL Editor

create extension if not exists pgcrypto;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  token text not null unique,
  device_id text,
  is_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.kintai (
  id bigint generated by default as identity primary key,
  name text not null,
  date date not null,
  check_in text,
  check_out text,
  checkin_at timestamptz,
  checkout_at timestamptz,
  work_hours numeric(5,2) not null default 0,
  remarks text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_devices (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  device_id text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, device_id)
);

create index if not exists idx_users_name
  on public.users (name);

create index if not exists idx_users_token
  on public.users (token);

create index if not exists idx_users_device_id
  on public.users (device_id);

create index if not exists idx_users_is_admin
  on public.users (is_admin);

create index if not exists idx_kintai_name_date
  on public.kintai (name, date);

create index if not exists idx_kintai_date
  on public.kintai (date);

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_users_updated_at on public.users;
create trigger set_users_updated_at
before update on public.users
for each row
execute function public.set_updated_at();

drop trigger if exists set_kintai_updated_at on public.kintai;
create trigger set_kintai_updated_at
before update on public.kintai
for each row
execute function public.set_updated_at();

drop trigger if exists set_user_devices_updated_at on public.user_devices;
create trigger set_user_devices_updated_at
before update on public.user_devices
for each row
execute function public.set_updated_at();

alter table public.users enable row level security;
alter table public.kintai enable row level security;
alter table public.user_devices enable row level security;

create policy "Allow anon full access to users"
on public.users
for all
using (true)
with check (true);

create policy "Allow anon full access to kintai"
on public.kintai
for all
using (true)
with check (true);

create policy "Allow anon full access to user_devices"
on public.user_devices
for all
using (true)
with check (true);
